//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interlacer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interlacer.StringRes_EN", typeof(StringRes_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addPicTooltip {
            get {
                return ResourceManager.GetString("addPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string clearAllTooltip {
            get {
                return ResourceManager.GetString("clearAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file {0} may be corrupted..
        /// </summary>
        internal static string configFileCorruptError {
            get {
                return ResourceManager.GetString("configFileCorruptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copyPicTooltip {
            get {
                return ResourceManager.GetString("copyPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string doneMessage {
            get {
                return ResourceManager.GetString("doneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of images is empty.
        /// </summary>
        internal static string emptyListError {
            get {
                return ResourceManager.GetString("emptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be opened. File probably does not exist..
        /// </summary>
        internal static string fileNotFoundError {
            get {
                return ResourceManager.GetString("fileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic.
        /// </summary>
        internal static string filterCubic {
            get {
                return ResourceManager.GetString("filterCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string filterLanczos {
            get {
                return ResourceManager.GetString("filterLanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string filterLinear {
            get {
                return ResourceManager.GetString("filterLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest neighbour.
        /// </summary>
        internal static string filterNearestNeighbor {
            get {
                return ResourceManager.GetString("filterNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image dimensions differ. Do you want to crop them to minimum width and minimum height?.
        /// </summary>
        internal static string imageDimensionError {
            get {
                return ResourceManager.GetString("imageDimensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be loaded..
        /// </summary>
        internal static string imageLoadError {
            get {
                return ResourceManager.GetString("imageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0} could not be saved..
        /// </summary>
        internal static string imageSaveError {
            get {
                return ResourceManager.GetString("imageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be saved. Check writing privileges and make sure there is enough space..
        /// </summary>
        internal static string imageSaveError2 {
            get {
                return ResourceManager.GetString("imageSaveError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlacing failed. Check interlacing parameters..
        /// </summary>
        internal static string interlacingError {
            get {
                return ResourceManager.GetString("interlacingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string langCzech {
            get {
                return ResourceManager.GetString("langCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading graphics library.
        ///Make sure Visual C++ Redistributable is installed..
        /// </summary>
        internal static string libraryLoadError {
            get {
                return ResourceManager.GetString("libraryLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        internal static string loadTooltip {
            get {
                return ResourceManager.GetString("loadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory..
        /// </summary>
        internal static string memoryError {
            get {
                return ResourceManager.GetString("memoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string moveDownTooltip {
            get {
                return ResourceManager.GetString("moveDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string moveUpTooltip {
            get {
                return ResourceManager.GetString("moveUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string nameListView {
            get {
                return ResourceManager.GetString("nameListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string orderListView {
            get {
                return ResourceManager.GetString("orderListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string pathListView {
            get {
                return ResourceManager.GetString("pathListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview could not be created.
        /// </summary>
        internal static string previewError {
            get {
                return ResourceManager.GetString("previewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string removePicTooltip {
            get {
                return ResourceManager.GetString("removePicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace image.
        /// </summary>
        internal static string replaceTooltip {
            get {
                return ResourceManager.GetString("replaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse list.
        /// </summary>
        internal static string revertTooltip {
            get {
                return ResourceManager.GetString("revertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string saveTooltip {
            get {
                return ResourceManager.GetString("saveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort images by their ending number.
        /// </summary>
        internal static string sortTooltip {
            get {
                return ResourceManager.GetString("sortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        internal static string unitsInches {
            get {
                return ResourceManager.GetString("unitsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File  {0} has wrong format..
        /// </summary>
        internal static string wrongFormatError {
            get {
                return ResourceManager.GetString("wrongFormatError", resourceCulture);
            }
        }
    }
}
