//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interlacer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interlacer.StringRes_CZ", typeof(StringRes_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        internal static string addPicTooltip {
            get {
                return ResourceManager.GetString("addPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat vše.
        /// </summary>
        internal static string clearAllTooltip {
            get {
                return ResourceManager.GetString("clearAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurační soubor {0} je pravděpodobně poškozen..
        /// </summary>
        internal static string configFileCorruptError {
            get {
                return ResourceManager.GetString("configFileCorruptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopírovat.
        /// </summary>
        internal static string copyPicTooltip {
            get {
                return ResourceManager.GetString("copyPicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotovo.
        /// </summary>
        internal static string doneMessage {
            get {
                return ResourceManager.GetString("doneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam obrázků je prázdný..
        /// </summary>
        internal static string emptyListError {
            get {
                return ResourceManager.GetString("emptyListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo otevřít. 
        ///Soubor pravděpodobně neexistuje..
        /// </summary>
        internal static string fileNotFoundError {
            get {
                return ResourceManager.GetString("fileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubický.
        /// </summary>
        internal static string filterCubic {
            get {
                return ResourceManager.GetString("filterCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string filterLanczos {
            get {
                return ResourceManager.GetString("filterLanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineární.
        /// </summary>
        internal static string filterLinear {
            get {
                return ResourceManager.GetString("filterLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejbližší soused.
        /// </summary>
        internal static string filterNearestNeighbor {
            get {
                return ResourceManager.GetString("filterNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázky nejsou stejně velké. Chcete je oříznout na nejmenší šířku a nejmenší výšku?.
        /// </summary>
        internal static string imageDimensionError {
            get {
                return ResourceManager.GetString("imageDimensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo načíst..
        /// </summary>
        internal static string imageLoadError {
            get {
                return ResourceManager.GetString("imageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázek {0} se nepodařilo uložit..
        /// </summary>
        internal static string imageSaveError {
            get {
                return ResourceManager.GetString("imageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} se nepodařilo uložit. Překontrolujte zda máte právo zápisu, nebo dostatek místa..
        /// </summary>
        internal static string imageSaveError2 {
            get {
                return ResourceManager.GetString("imageSaveError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prokládání selhalo. Pravděpodobnou příčinou je chybné nastavení prokládacích parametrů. Zkontrolujte, zda některý z parametrů není nulový, příliš malý či příliš velký..
        /// </summary>
        internal static string interlacingError {
            get {
                return ResourceManager.GetString("interlacingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čeština.
        /// </summary>
        internal static string langCzech {
            get {
                return ResourceManager.GetString("langCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angličtina.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při načítání grafické knihovny.
        ///Pravděpodobnou příčinou je chybějící Visual C++ Redistributable.
        /// </summary>
        internal static string libraryLoadError {
            get {
                return ResourceManager.GetString("libraryLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst projekt.
        /// </summary>
        internal static string loadTooltip {
            get {
                return ResourceManager.GetString("loadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace nemá k dispozici dostatek operační paměti..
        /// </summary>
        internal static string memoryError {
            get {
                return ResourceManager.GetString("memoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posunout o jeden dolů.
        /// </summary>
        internal static string moveDownTooltip {
            get {
                return ResourceManager.GetString("moveDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posunout o jeden nahoru.
        /// </summary>
        internal static string moveUpTooltip {
            get {
                return ResourceManager.GetString("moveUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string nameListView {
            get {
                return ResourceManager.GetString("nameListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí.
        /// </summary>
        internal static string orderListView {
            get {
                return ResourceManager.GetString("orderListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesta.
        /// </summary>
        internal static string pathListView {
            get {
                return ResourceManager.GetString("pathListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhled se nepodařilo vytvořit..
        /// </summary>
        internal static string previewError {
            get {
                return ResourceManager.GetString("previewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat.
        /// </summary>
        internal static string removePicTooltip {
            get {
                return ResourceManager.GetString("removePicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahradit obrázek za jiný.
        /// </summary>
        internal static string replaceTooltip {
            get {
                return ResourceManager.GetString("replaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otočit list obrázků.
        /// </summary>
        internal static string revertTooltip {
            get {
                return ResourceManager.GetString("revertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit projekt.
        /// </summary>
        internal static string saveTooltip {
            get {
                return ResourceManager.GetString("saveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadí obrázky podle koncového čísla.
        /// </summary>
        internal static string sortTooltip {
            get {
                return ResourceManager.GetString("sortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palce.
        /// </summary>
        internal static string unitsInches {
            get {
                return ResourceManager.GetString("unitsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor {0} má chybný formát..
        /// </summary>
        internal static string wrongFormatError {
            get {
                return ResourceManager.GetString("wrongFormatError", resourceCulture);
            }
        }
    }
}
